version: 1
update_configs:
  # Keep package.json (& lockfiles) up to date as soon as
  # new versions are published to the npm registry
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "[skip netlify]"
